<h1 class="hidden">Kitchen / Bath Remodel on a Shoestring Budget</h1>

This kitchen/bath remodel was on a shoe string budget...
<div><a href="http://picasaweb.google.com/lh/photo/KJZN9poslEKG83pP36fblg?feat=embedwebsite"><img alt="" src="http://lh6.ggpht.com/_nQj0J2KK4S8/S38yy5VTdvI/AAAAAAAAAGU/40pBCZeVjfw/s144/1-1.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/PfK8-2xca5SbmGgzAovqcA?feat=embedwebsite"><img alt="" src="http://lh6.ggpht.com/_nQj0J2KK4S8/S38yzGkCQdI/AAAAAAAAAGY/CTwbMzh6M4M/s144/1-2.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/RExOUVvqnkoaLocT27jLZg?feat=embedwebsite"><img alt="" src="http://lh6.ggpht.com/_nQj0J2KK4S8/S38yzEWuVBI/AAAAAAAAAGc/KDVg_HJWvqg/s144/1-3.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/S_AsWzN04n4hNs_68umDzA?feat=embedwebsite"><img alt="" src="http://lh5.ggpht.com/_nQj0J2KK4S8/S38zBHU1_cI/AAAAAAAAAGo/p-nbTL7uoQ0/s144/1-6.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/-cwBBUHz32u56Dwk3Rx3Dw?feat=embedwebsite"><img alt="" src="http://lh6.ggpht.com/_nQj0J2KK4S8/S38yzGx-MqI/AAAAAAAAAGg/XStntjC9kBA/s144/1-4.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/nySP9-hweEuZoDTi5RtsRg?feat=embedwebsite"><img alt="" src="http://lh4.ggpht.com/_nQj0J2KK4S8/S38yzOdIrhI/AAAAAAAAAGk/wsnjojBpLjg/s144/1-5.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/YnW-aT176zkLpNiVswrg4g?feat=embedwebsite"><img alt="" src="http://lh3.ggpht.com/_nQj0J2KK4S8/S38zBHjXCrI/AAAAAAAAAGs/riun9ln9VJw/s144/1.jpeg" /></a></div>
The work had to be put together saving as much as possible at every step.

The client mail ordered these cabinets in and we assembled them on sight.

Granite countertops were preferred, so we ordered some granite 12x12 tiles online and built the countertops.

With upgraded electrical needs came a second electric panel and we worked a new washer dryer hook up into the kitchen area as well (few of these condos have a W/D).

Time was of an essence! From start to finish we had three weeks and the bathroom was included as an after thought. We also replaced closet doors and trim during this time, installed travertine stone floors, and repaired drywall from an upstairs leak that occurred the week before we started.

On time and on budget!
<div><a href="http://picasaweb.google.com/lh/photo/xOgZmPxlDHQkLSYxksCVCQ?feat=embedwebsite"><img alt="" src="http://lh4.ggpht.com/_nQj0J2KK4S8/S38zBatLD_I/AAAAAAAAAGw/kdctblDSSoc/s144/1-1.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/xo_ClmXmkD2K_v8aDAOr8Q?feat=embedwebsite"><img alt="" src="http://lh5.ggpht.com/_nQj0J2KK4S8/S38zBYjAqII/AAAAAAAAAG0/mYJgsHuxonA/s144/1-4.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/z1gtKFeh8gfy5WEaz9bVFw?feat=embedwebsite"><img alt="" src="http://lh5.ggpht.com/_nQj0J2KK4S8/S38zBq5PXRI/AAAAAAAAAG4/nGlleQkh7Z4/s144/1-6.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/7mkXS9qf6KHGdV0usZHBXA?feat=embedwebsite"><img alt="" src="http://lh3.ggpht.com/_nQj0J2KK4S8/S38zQ8JQlFI/AAAAAAAAAG8/WWjW1EOKqhg/s144/1-7.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/q2xcetF-23SS-YsL_etztg?feat=embedwebsite"><img alt="" src="http://lh3.ggpht.com/_nQj0J2KK4S8/S38zRA7Xz6I/AAAAAAAAAHA/qpdZzUJvNxw/s144/1-8.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/I-ETLNxUjg7Ty1HgFNIUPw?feat=embedwebsite"><img alt="" src="http://lh5.ggpht.com/_nQj0J2KK4S8/S38zaCr5fGI/AAAAAAAAAHU/UqKAJdVScVg/s144/1-13.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/b-IUdy7qQ_I81o0GEq5m_g?feat=embedwebsite"><img alt="" src="http://lh4.ggpht.com/_nQj0J2KK4S8/S38zRSdvVTI/AAAAAAAAAHI/Oo_RyC41MUk/s144/1-10.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/eri5k-bT6mtzkXuhWNsdCQ?feat=embedwebsite"><img alt="" src="http://lh6.ggpht.com/_nQj0J2KK4S8/S38zRUYlrQI/AAAAAAAAAHE/yF6M0Sma2vQ/s144/1-9.jpeg" /></a><a href="http://picasaweb.google.com/lh/photo/Lq9fae6DwNgjmKmQHK_Wuw?feat=embedwebsite"><img alt="" src="http://lh3.ggpht.com/_nQj0J2KK4S8/S38zaMU7kuI/AAAAAAAAAHQ/fdPvv1h9pBA/s144/1-12.jpeg" /></a></div>